default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: password
  database: comee_price_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: comee_price_development

test:
  <<: *default
  database: comee_test
  
production:
  <<: *default
  database: orderConverter_production
  username: orderConverter
  password: <%= ENV["ORDERCONVERTER_DATABASE_PASSWORD"] %>
